[versions]
spring-boot = "3.1.5"
spring-dependency-management = "1.1.3"
either-java = "2.9.0"

[libraries]
either-java = { module = "com.spencerwi:Either.java", version.ref = "either-java" }

[bundles]

[plugins]
springframework-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }